apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
  ports:
    - name: gateway
      port: {{ .Values.ports.gateway }}
      targetPort: gateway
      protocol: TCP
    - name: console
      port: {{ .Values.ports.console }}
      targetPort: console
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
