// Command nexus-evalbatch runs an offline regression-evaluation pass over a
// JSON Lines dataset. Each case is scored by the external Python eval service
// (DeepEval/RAGAS) via the same RemoteEvaluator used by the online pipeline.
//
// Cases without a recorded "output" can be generated by pointing -gateway-url
// at a running Nexus (or any OpenAI-compatible endpoint). The aggregated report
// is printed and optionally written as JSON; when a -baseline report is given,
// the command exits non-zero if any metric's mean score regressed beyond
// -tolerance, making it suitable for CI gating.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/ffxnexus/nexus/internal/evalbatch"
	"github.com/ffxnexus/nexus/internal/evals"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(2)
	}
}

func run() error {
	var (
		dataset     = flag.String("dataset", "", "path to JSONL dataset (required)")
		serviceURL  = flag.String("service-url", envOr("NEXUS_EVAL_SERVICE_URL", ""), "Python eval service base URL (required)")
		metricsCSV  = flag.String("metrics", envOr("NEXUS_EVAL_SERVICE_METRICS", "answer_relevancy,toxicity,bias"), "comma-separated metric ids")
		timeout     = flag.Duration("timeout", 60*time.Second, "per-case eval timeout")
		concurrency = flag.Int("concurrency", 4, "concurrent eval workers")
		gatewayURL  = flag.String("gateway-url", "", "OpenAI-compatible endpoint to generate missing outputs (optional)")
		apiKey      = flag.String("api-key", os.Getenv("NEXUS_API_KEY"), "bearer token for -gateway-url")
		genModel    = flag.String("gen-model", "", "default model for generation when a case omits one")
		baseline    = flag.String("baseline", "", "baseline report JSON to compare against (optional)")
		tolerance   = flag.Float64("tolerance", 0.05, "max allowed mean-score drop vs baseline before failing")
		outPath     = flag.String("out", "", "write the report JSON to this path (optional)")
		detail      = flag.Bool("detail", false, "include per-case scores in the JSON report")
	)
	flag.Parse()

	if *dataset == "" {
		return fmt.Errorf("-dataset is required")
	}
	if *serviceURL == "" {
		return fmt.Errorf("-service-url (or NEXUS_EVAL_SERVICE_URL) is required")
	}

	cases, err := evalbatch.LoadDataset(*dataset)
	if err != nil {
		return fmt.Errorf("load dataset: %w", err)
	}

	ctx := context.Background()

	// Generate missing outputs via the gateway when configured.
	if *gatewayURL != "" {
		gc := &genClient{base: strings.TrimRight(*gatewayURL, "/"), key: *apiKey, model: *genModel, hc: &http.Client{Timeout: *timeout}}
		generated := 0
		for i := range cases {
			if cases[i].Output != "" {
				continue
			}
			out, err := gc.generate(ctx, cases[i])
			if err != nil {
				return fmt.Errorf("generate output for %s: %w", cases[i].ID, err)
			}
			cases[i].Output = out
			generated++
		}
		fmt.Fprintf(os.Stderr, "generated %d output(s) via %s\n", generated, *gatewayURL)
	}

	evaluator := evals.NewRemoteEvaluator(evals.RemoteConfig{
		BaseURL: *serviceURL,
		Metrics: splitCSV(*metricsCSV),
		Timeout: *timeout,
	})
	if evaluator == nil {
		return fmt.Errorf("invalid -service-url")
	}

	runner := &evalbatch.Runner{Eval: evaluator, Concurrency: *concurrency, Timeout: *timeout}
	results := runner.Run(ctx, cases)
	report := evalbatch.BuildReport(*dataset, results, *detail)

	report.RenderText(os.Stdout)

	if *outPath != "" {
		f, err := os.Create(*outPath)
		if err != nil {
			return fmt.Errorf("create -out: %w", err)
		}
		if err := report.WriteJSON(f); err != nil {
			f.Close()
			return fmt.Errorf("write report: %w", err)
		}
		f.Close()
		fmt.Fprintf(os.Stderr, "wrote report to %s\n", *outPath)
	}

	if *baseline != "" {
		base, err := evalbatch.LoadReport(*baseline)
		if err != nil {
			return fmt.Errorf("load baseline: %w", err)
		}
		regs := report.CompareBaseline(base, *tolerance)
		if len(regs) > 0 {
			fmt.Fprintf(os.Stderr, "\nREGRESSIONS (tolerance %.3f):\n", *tolerance)
			for _, r := range regs {
				fmt.Fprintf(os.Stderr, "  %-26s %.3f -> %.3f (%.3f)\n", r.Metric, r.BaselineMean, r.CurrentMean, r.Delta)
			}
			os.Exit(1)
		}
		fmt.Fprintln(os.Stderr, "\nno regressions vs baseline")
	}
	return nil
}

func splitCSV(s string) []string {
	var out []string
	for _, p := range strings.Split(s, ",") {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, p)
		}
	}
	return out
}

func envOr(key, def string) string {
	if v := strings.TrimSpace(os.Getenv(key)); v != "" {
		return v
	}
	return def
}

// genClient calls an OpenAI-compatible chat/completions endpoint to produce the
// output for a case that has none.
type genClient struct {
	base  string
	key   string
	model string
	hc    *http.Client
}

func (g *genClient) generate(ctx context.Context, c evalbatch.Case) (string, error) {
	model := c.Model
	if model == "" {
		model = g.model
	}
	if model == "" {
		return "", fmt.Errorf("no model set on case and no -gen-model default")
	}
	body, _ := json.Marshal(map[string]any{
		"model":    model,
		"messages": c.ChatMessages(),
	})
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, g.base+"/v1/chat/completions", bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	if g.key != "" {
		req.Header.Set("Authorization", "Bearer "+g.key)
	}
	resp, err := g.hc.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("gateway %d: %s", resp.StatusCode, truncate(string(raw), 200))
	}
	var parsed struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.Unmarshal(raw, &parsed); err != nil {
		return "", err
	}
	if len(parsed.Choices) == 0 {
		return "", fmt.Errorf("gateway returned no choices")
	}
	return parsed.Choices[0].Message.Content, nil
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
