apiVersion: 1

providers:
  - name: 'nexus-pre-baked'
    orgId: 1
    folder: 'Nexus'
    type: file
    disableDeletion: true
    updateIntervalSeconds: 30
    allowUiUpdates: false
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: false
